import {
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiNodedotjs,
  SiDocker,
  SiReact,
  SiStyledcomponents,
  SiNextdotjs,
  SiPostgresql,
  SiTailwindcss,
  SiPrisma,
  SiLinux,
  SiEslint,
  SiPrettier,
  SiExpo,
  SiGit,
  SiGithub,
  SiPython,
  SiSass,
  SiVite,
} from "react-icons/si";
import { TbDatabase } from "react-icons/tb";

export const stackData = [
  { title: "TypeScript", img: SiTypescript },
  { title: "JavaScript", img: SiJavascript },
  { title: "HTML", img: SiHtml5 },
  { title: "CSS", img: SiCss3 },
  { title: "Docker", img: SiDocker },
  { title: "Node JS", img: SiNodedotjs },
  { title: "Styled Components", img: SiStyledcomponents },
  { title: "React", img: SiReact },
  { title: "Next.js", img: SiNextdotjs },
  { title: "PostgreSQL", img: SiPostgresql },
  { title: "Tailwind CSS", img: SiTailwindcss },
  { title: "Prisma", img: SiPrisma },
  { title: "TypeORM", img: TbDatabase },
  { title: "Linux", img: SiLinux },
  { title: "ESLint + Prettier", img: SiEslint },
  { title: "React Native", img: SiReact },
  { title: "Expo", img: SiExpo },
  { title: "Git & GitHub", img: SiGithub },
  { title: "Python", img: SiPython },
  { title: "Sass", img: SiSass },
  { title: "Vite", img: SiVite },
];
